resetdb:
	rm -f main.sqlite3
	sqlite3 main.sqlite3 < tools/schema.sql
	ssh illuvatar -- 'sudo systemctl stop hacks26'
	scp main.sqlite3 illuvatar:/home/hacks26
	ssh illuvatar -- 'sudo systemctl start hacks26'

deploy:
	cargo build --release
	ssh illuvatar -- 'sudo systemctl stop hacks26'
	scp target/release/hacks26 illuvatar:/home/hacks26/bin/hacks26
	ssh illuvatar -- 'sudo chown -R hacks26:hacks26 /home/hacks26/'
	ssh illuvatar -- 'sudo chmod -R g+w /home/hacks26'
	ssh illuvatar -- 'sudo systemctl start hacks26'
