CREATE TABLE IF NOT EXISTS Users (
	id       INTEGER PRIMARY KEY,
	username TEXT UNIQUE NOT NULL,
	name     TEXT NOT NULL,
	password TEXT NOT NULL,
	nhood    INTEGER NOT NULL,
	phone    TEXT NOT NULL
) STRICT;

CREATE TABLE IF NOT EXISTS Posts (
	id         INTEGER PRIMARY KEY,
	timestamp  INTEGER NOT NULL,
	title      TEXT NOT NULL,
	request    TEXT NOT NULL,
	offer      TEXT NOT NULL,
	author     INTEGER NOT NULL,
	FOREIGN KEY(author) REFERENCES Users(id),
	FOREIGN KEY(accepter) REFERENCES Users(id)
) STRICT;

CREATE TABLE IF NOT EXISTS Matches (
	id       INTEGER PRIMARY KEY,
	author   INTEGER NOT NULL,
	accepter INTEGER,
	post     INTEGER NOT NULL,
	FOREIGN KEY(author) REFERENCES Users(id),
	FOREIGN KEY(accepter) REFERENCES Users(id),
	FOREIGN KEY(post) REFERENCES Posts(id)
) STRICT;

CREATE TABLE IF NOT EXISTS Sessions (
	uuid     BLOB    PRIMARY KEY,
	user     INTEGER NOT NULL,
	aud      TEXT    NOT NULL,
	exp      INTEGER NOT NULL,
	FOREIGN KEY(user) REFERENCES Users(id)
) STRICT;
